### ISSUE TITLE
Can Frame hide Shopify sidebar?

### ISSUE THREAD

**Issue by mariusa** [ownego/polaris-vue#183]
The Frame docs have a screenshot with a full-screen app.
For me, app using Frame still shows the Shopify sidebar. Is it actually possible to hide Shopify sidebar and leave more screen for the app?

Found the same question here:
https://community.shopify.com/c/shopify-apis-and-sdks/hiding-shopify-ui-elements-in-an-embedded-app/td-p/1250926

Thanks

**Comment by juzser** [comment]
@mariusa the answer is Yes, you don't have to do anything, just do not use the `#navigation` slot, then the screen will be full.

Actually, I'm also using the Frame without navigation for my apps.

**Comment by mariusa** [comment]
Hi & thanks for reply,

I removed #navigation slot, but only the app sidebar was removed. Shopify sidebar still shows:
![Screenshot from 2023-03-21 08-50-29](https://user-images.githubusercontent.com/1283842/226536004-e682804e-875a-42f3-92e7-90200c608fbc.png)

So it's not possible to have exactly this full screen for the app? 

![Screenshot from 2023-03-21 08-52-41](https://user-images.githubusercontent.com/1283842/226536275-e2b66230-9a91-48eb-9896-12c897eb54b0.png)

**Comment by juzser** [comment]
@mariusa Seem likes you do not fully understand the embedded app from Shopify... I think you should read the Shopify document first. 
There is a way to do fullscreen app mode for embedded app is using appBridge full screen method. Otherwise, if you want your app to be fullscreen, you have to build the un-embedded app (an separated app system) 

I'm closing this question here. You should read the documentation and understand Shopify system first.
