### ISSUE TITLE
Can not import component's type

### ISSUE THREAD

**Issue by nguyenvanduocit** [ownego/polaris-vue#373]
As you can see in the image below, it is not possible to import component types:

![image](https://github.com/ownego/polaris-vue/assets/1256953/8eaffd2c-fbe4-43a7-a6bb-d6c11a400334)

I think the reason for this is that the type file uses aliases, and consumer project cannot resolve aliases in that file (because consumer project does not know about this alias config)

I have done some research, and it seems that there is no way to fix this other than to write a post-script to replace the path.

**Comment by nguyenvanduocit** [comment]
The same issue here: https://github.com/vuejs/language-tools/issues/863

**Comment by juzser** [comment]
@nguyenvanduocit Thank a lot for the PR!
The v2.0.5 has been released to fix this issue. 
We're not using `resolve-tspaths` as your suggestion because of some reasons behind the package and build process. 

I'm using `vite-plugin-dts` to generate the types based on tsconfig, by the way, still there are 4 relative paths in the built type file, I'm still investigating. 
But currently it works and covers ~99% types of the components. Check it out.

Thank you.

**Comment by nguyenvanduocit** [comment]
Thank you for the update.
